### ISSUE TITLE
Implement check interval

### ISSUE THREAD

**Issue by Pro** [arrizer/PutIO-Perl-folder-sync#7]
Add function to automatically check each hour (time span can define user) if new files are available.

Because if running the script with crontab and it is already running because a download takes longer than the crontab interval files will be downloaded twice or even more often.

**Comment by arrizer** [comment]
I will implement a PID file to check if another instance of the script is already running.

**Comment by arrizer** [comment]
PID file single instance check is implemented since 0.6
